In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn import preprocessing
from sklearn.ensemble import ExtraTreesClassifier
le = preprocessing.LabelEncoder()
# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.


train = pd.read_csv("../input/train.csv")
train = train.fillna(method='ffill').fillna(method='bfill')


for col in train:
    currcol = train[col]
    boo = np.issubdtype(currcol.dtype, np.number)
    if not boo:
        labels = list(set(currcol))
        le.fit(labels)
        newcol = le.transform(currcol)
        train[col] = newcol
x_train = train[['Pclass','Name','Sex','Age','SibSp','Parch','Ticket','Fare','Cabin','Embarked']]
y_train = train['Survived']
train.head()


model = ExtraTreesClassifier(n_estimators=1000, min_samples_leaf=2)
model.fit(x_train, y_train)
model.predict([[0,3,108,1,22.0,1,0,523,7.2500,81]])


test = pd.read_csv('../input/test.csv')
ids = list(test['PassengerId'])
test = test.fillna(method='ffill').fillna(method='bfill')
for col in test:
    currcol = test[col]
    labels = list(set(currcol))
    le.fit(labels)
    newcol = le.transform(currcol)
    test[col] = newcol
x_test = test[['Pclass','Name','Sex','Age','SibSp','Parch','Ticket','Fare','Cabin','Embarked']]
predictions = list(model.predict(x_test))

twodarray = []
for i in range(418):
    l =  [ids[i], predictions[i]]
    twodarray.append(l)
df = pd.DataFrame(twodarray, columns=['PassengerId', 'Survived'])
df = df[['PassengerId', 'Survived']]

df.to_csv('Titanic_Solution.csv', index=False)

print('Done')

['train.csv', 'gender_submission.csv', 'test.csv']
Done

In [3]:
train

     PassengerId  Survived  Pclass    ...         Fare  Cabin  Embarked
0              1         0       3    ...       7.2500     81         2
1              2         1       1    ...      71.2833     81         0
2              3         1       3    ...       7.9250     81         2
3              4         1       1    ...      53.1000     55         2
4              5         0       3    ...       8.0500     55         2
5              6         0       3    ...       8.4583     55         1
6              7         0       1    ...      51.8625    129         2
7              8         0       3    ...      21.0750    129         2
8              9         1       3    ...      11.1333    129         2
9             10         1       2    ...      30.0708    129         0
10            11         1       3    ...      16.7000    145         2
11            12         1       1    ...      26.5500     49         2
12            13         0       3    ...       8.0500     49         2
13            14         0       3    ...      31.2750     49         2
14            15         0       3    ...       7.8542     49         2
15            16         1       2    ...      16.0000     49         2
16            17         0       3    ...      29.1250     49         1
17            18         1       2    ...      13.0000     49         2
18            19         0       3    ...      18.0000     49         2
19            20         1       3    ...       7.2250     49         0
20            21         0       2    ...      26.0000     49         2
21            22         1       2    ...      13.0000    111         2
22            23         1       3    ...       8.0292    111         1
23            24         1       1    ...      35.5000     13         2
24            25         0       3    ...      21.0750     13         2
25            26         1       3    ...      31.3875     13         2
26            27         0       3    ...       7.2250     13         0
27            28         0       1    ...     263.0000     63         2
28            29         1       3    ...       7.8792     63         1
29            30         0       3    ...       7.8958     63         2
..           ...       ...     ...    ...          ...    ...       ...
861          862         0       2    ...      11.5000    119         2
862          863         1       1    ...      25.9292     94         2
863          864         0       3    ...      69.5500     94         2
864          865         0       2    ...      13.0000     94         2
865          866         1       2    ...      13.0000     94         2
866          867         1       2    ...      13.8583     94         0
867          868         0       1    ...      50.4958      6         2
868          869         0       3    ...       9.5000      6         2
869          870         1       3    ...      11.1333      6         2
870          871         0       3    ...       7.8958      6         2
871          872         1       1    ...      52.5542    102         2
872          873         0       1    ...       5.0000     34         2
873          874         0       3    ...       9.0000     34         2
874          875         1       2    ...      24.0000     34         0
875          876         1       3    ...       7.2250     34         0
876          877         0       3    ...       9.8458     34         2
877          878         0       3    ...       7.8958     34         2
878          879         0       3    ...       7.8958     34         2
879          880         1       1    ...      83.1583     70         0
880          881         1       2    ...      26.0000     70         2
881          882         0       3    ...       7.8958     70         2
882          883         0       3    ...      10.5167     70         2
883          884         0       2    ...      10.5000     70         2
884          885         0       3    ...       7.0500     70         2
885          886         0       3    ...      29.1250     70         1
886          887         0       2    ...      13.0000     70         2
887          888         1       1    ...      30.0000     30         2
888          889         0       3    ...      23.4500     30         2
889          890         1       1    ...      30.0000     60         0
890          891         0       3    ...       7.7500     60         1

[891 rows x 12 columns]

In [4]:
test

     PassengerId  Pclass  Name  Sex    ...     Ticket  Fare  Cabin  Embarked
0              0       2   206    1    ...        152    24     12         1
1              1       2   403    0    ...        221     5     12         2
2              2       1   269    1    ...         73    41     12         1
3              3       2   408    1    ...        147    34     12         2
4              4       2   178    0    ...        138    46     12         2
5              5       2   366    1    ...        261    37     12         2
6              6       2    84    0    ...        158    14     12         1
7              7       1    57    1    ...         84   100     12         2
8              8       2     4    0    ...        100     8     12         0
9              9       2   103    1    ...        269    89     12         2
10            10       2   187    1    ...        195    29     12         2
11            11       0   196    1    ...        259    93     12         2
12            12       0   352    0    ...         52   149     12         2
13            13       1   184    1    ...         74    93     12         2
14            14       0    69    0    ...        362   135     60         2
15            15       1   415    0    ...        343    96     60         0
16            16       1   204    1    ...         60    47     60         1
17            17       2    21    1    ...        119     7     60         0
18            18       2   188    0    ...        356    30     60         2
19            19       2    20    0    ...        120     7     60         0
20            20       0   324    1    ...        316   133     60         0
21            21       2   284    1    ...        277     1     60         2
22            22       0   138    0    ...        314   108     60         2
23            23       0   406    1    ...        313   136     60         0
24            24       0   329    0    ...        319   166     15         0
25            25       2   318    1    ...        273    61     15         2
26            26       0   288    0    ...         14   137     10         0
27            27       2    97    1    ...        121     7     10         0
28            28       0    44    1    ...         11   104      2         2
29            29       2   339    1    ...        104    82      2         0
..           ...     ...   ...  ...    ...        ...   ...    ...       ...
388          388       2    58    1    ...        225    19     32         1
389          389       2   292    1    ...        205    81     32         2
390          390       0   294    1    ...         32   152      8         2
391          391       0   231    0    ...        311   114     53         2
392          392       2     0    1    ...        281    78     53         2
393          393       1   155    1    ...        282    42     53         2
394          394       2   214    1    ...        146    83     53         2
395          395       0   349    0    ...         37   134     30         2
396          396       2    79    1    ...        244     9     30         1
397          397       0   150    0    ...         36   147     11         0
398          398       2   224    1    ...        176    20     11         2
399          399       2    83    1    ...         53    18     11         1
400          400       0    37    0    ...        238   160     40         2
401          401       1   151    1    ...        128    80     40         2
402          402       0   153    0    ...          7   133     40         0
403          403       0    64    1    ...         12   122     40         2
404          404       0   149    1    ...         44    96     58         0
405          405       1   279    1    ...        342    55     57         0
406          406       1   386    1    ...        129    42     57         2
407          407       0   400    1    ...         13   162     42         0
408          408       2   316    0    ...        160    16     42         1
409          409       2   296    0    ...        351    53     42         2
410          410       2   273    0    ...        228    19     42         1
411          411       0   262    0    ...         48   151     41         1
412          412       2   172    0    ...        184    20     41         2
413          413       2   353    1    ...        267    31     41         2
414          414       0   283    0    ...        324   154     22         0
415          415       2   332    1    ...        346     9     22         2
416          416       2   384    1    ...        220    31     22         2
417          417       2   302    1    ...        105    84     22         0

[418 rows x 11 columns]

In [5]:
df

     PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
5            897         0
6            898         1
7            899         1
8            900         1
9            901         0
10           902         0
11           903         0
12           904         1
13           905         0
14           906         1
15           907         1
16           908         0
17           909         0
18           910         1
19           911         1
20           912         0
21           913         0
22           914         1
23           915         0
24           916         1
25           917         0
26           918         1
27           919         0
28           920         0
29           921         0
..           ...       ...
388         1280         0
389         1281         0
390         1282         0
391         1283         1
392         1284         0
393         1285         0
394         1286         0
395         1287         1
396         1288         0
397         1289         1
398         1290         0
399         1291         0
400         1292         1
401         1293         0
402         1294         1
403         1295         0
404         1296         1
405         1297         0
406         1298         0
407         1299         0
408         1300         1
409         1301         1
410         1302         1
411         1303         1
412         1304         1
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]